= App Lifecycle
:navtitle: App Lifecycle

In the previous lab, you explored the Cluster Lifecycle functionality in RHACM. This allowed you to register/import an OpenShift® cluster to RHACM, which you can now use to deploy applications.

This module will walk you through the Application Lifecycle functionality in RHACM.
Read and follow the instructions carefully.
At the end of this module, you'll have deployed the GitOps operator and 1 new application.

== Before You Begin

Some clarifications:

* The Governance module is a prerequesite to this module, as it provides a controlled and automated deployment of the the OpenShift GitOps operator, based on https://argo-cd.readthedocs.io/en/stable/[ArgoCD]. If you haven't gone through the Governance module yet, please do it or feel free to install the OpenShift GitOps operator manually via the OpenShift Software catalog.
* RHACM offers 3 different integratopm approaches for GitOps integration: Push model, Pull model, and Agent model. Each pattern has its own usecases and benefits, but in this demo, we will focus on the push model. 

== Integrating RHACM and GitOps

With the GitOps operator installed, we now need to make sure ArgoCD clusters inventory is synced with RHACM clusters inventory, so users can leverage the integration and deploy application to the fleet of clusters.
