= Governance
:navtitle: Governance

This page walks you through the Governance module in RHACM.
Read and follow the instructions carefully.
At the end of this module, you'll have deployed 2 new governance policies.

== Before You Begin

You will need:

* A content repository with your Antora lab instructions (or a fork of the https://github.com/rhpds/showroom_template_nookbag[template]).
See xref:content-repo.adoc[] if you have not created one yet.
* Access to the https://github.com/rhpds/agnosticv[agnosticv] repository to create or edit a catalog item.
* Familiarity with YAML and basic Ansible concepts.

== Path A -- OpenShift 4 Workload

Use this path when your lab provisions an OpenShift cluster and Showroom runs as a pod on that cluster.

=== 1. Add the collection to your catalog item

In your catalog item's `common.yaml`, declare the Showroom collection as a dependency:

[source,yaml,subs="+attributes"]
----
requirements_content:
  collections:
    - name: https://github.com/agnosticd/showroom.git
      type: git
      version: {showroom-collection-version}
----

=== 2. List the workloads

Add the Showroom workload to your workloads list.
Showroom should come **last** so that all infrastructure and credentials are available:

[source,yaml]
----
workloads:
  - ocp4_workload_my_operators        # your infra workloads first
  - agnosticd.showroom.ocp4_workload_showroom
----

If you want the OpenShift web console embedded as an iframe tab, add `ocp4_workload_ocp_console_embed` before the main Showroom workload.
See xref:ocp-integration.adoc[].
